# Number of levels in hierarchical k-means.
n_levels: 2

# Number of updates of centroids in the main k-means loop.
n_iters: 10

# Number of clusters in each level of hierarchical k-means.
# For efficiency in the first level, we run first a k-means
# with 100k clusters, then split each cluster into 100
# smaller ones to have 10M clusters.
n_clusters: 
  - 15_000
  - 100

# If > 1, run the level in two steps. First, k-means is executed once.
# Then, each obtained cluster is splitted into "n_split" smaller clusters,
# which are considered final and used in the subsequent level.
n_splits:
  - 1
  - 1

# Number of resampling steps in each level.
# For efficiency, we do not use resampling in the first level.
n_resampling_steps:
  - 5
  - 5

# Number of data points sampled from each cluster in the resampling steps.
# It is roughly half the average cluster size in each level.
sample_size:
  - 25
  - 10

# Specified if running only on a subset of the data pool.
# For example, we extract embeddings for all images in the data pool,
# but run the curation pipeline only on a deduplicated subset.
subset_indices_path: null
checkpoint_period: 1_000
dtype: float64
high_precision: float64
ngpus_per_node:
  - 2
  - 2
nnodes:
  - 1
  - 1
ncpus_per_gpu: 6
sampling_strategy: r
slurm_partition: null